# Generated by Django 3.1.7 on 2021-04-27 06:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('K_time', models.CharField(max_length=200)),
                ('K_location', models.CharField(max_length=200)),
                ('K_death', models.CharField(max_length=200)),
                ('K_injure', models.CharField(max_length=200)),
            ],
#            options={
#                'ordering': ('-pub_date',),
#            },
        ),
    ]
